[package]
name = "darth-compat"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
darth-commands = { path = "../darth-commands" }
darth-tools = { path = "../darth-tools" }
darth-runtime = { path = "../darth-runtime" }

[lints]
workspace = true
